version: '2'

services:
    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    redis:
        image: redis

    php:
        build: php7-fpm
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        links:
            - redis
        extra_hosts:
           - "cachecacheapi.dev:172.19.0.6"

    nginx:
        build: nginx
        ports:
            - 8080:80
        links:
            - node
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
    varnish:
        image: million12/varnish
        depends_on:
          - nginx
        environment:
          - VCL_CONFIG=/etc/varnish/default.vcl
          - CACHE_SIZE=128m
          - VARNISHD_PARAMS=-p default_ttl=60 -p default_grace=60
        ports:
          - '80:80'
        links:
          - nginx
        volumes:
          - ./varnish:/etc/varnish
    node:
      build: node
      volumes:
          - ./cachecacheapi:/app
      ports:
          - "3000:3000"
